name: Sync trends_data.db

on:
  repository_dispatch:
    types: [sync-db] # This listens for the event from the other workflow
  workflow_dispatch: # This allows you to still run it manually

jobs:
  sync-db:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository (target)
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACCESS_ALL_REPO }}
          
      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          repository: sudoghut/trends-story
          token: ${{ secrets.ACCESS_ALL_REPO }}
          path: source-repo
          
      - name: Copy database file from source
        run: cp source-repo/trends_data.db .
          
      - name: Check for changes
        id: check_changes
        run: |
          if git diff --quiet trends_data.db; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi
          
      - name: Commit and push if changed
        if: steps.check_changes.outputs.changed == 'true'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Sync: Update trends_data.db from trends-story repository"
          file_pattern: trends_data.db
          branch: main
