name: Download trends_data.db

on:
  push:
    paths:
      - 'trends_data.db'
  workflow_dispatch:

jobs:
  download-db:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the target repository
        uses: actions/checkout@v4
        with:
          repository: sudoghut/trends-story
          token: ${{ secrets.GH_TOKEN }}

      - name: Copy the database file
        run: |
          cp trends_data.db ${{ github.workspace }}

      - name: Commit the new database file
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Updated trends_data.db"
          branch: main
