name: Sync trends_data.db
on:
  push:
    branches:
      - main  # Or the branch you want to trigger this on
    paths:
      - 'trends_data.db'
  workflow_dispatch:

jobs:
  sync-db:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository (the target)
        uses: actions/checkout@v4
        
      - name: Checkout source repository (to get trends_data.db)
        uses: actions/checkout@v4
        with:
          repository: sudoghut/trends-story
          token: ${{ secrets.access_all_repo }}  # Make sure this matches your secret name
          path: trends-story-source
          
      - name: Copy the database file
        run: |
          cp trends-story-source/trends_data.db .
          
      - name: Commit the new database file
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Updated trends_data.db"
          branch: main
