name: Download trends_data.db

on:
  push:
    paths:
      - 'trends_data.db'
  workflow_dispatch:

jobs:
  download-db:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository (to get trends_data.db)
        uses: actions/checkout@v4
        with:
          path: source

      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          repository: sudoghut/trends-story
          token: ${{ secrets.access_all_repo }}
          path: target

      - name: Copy the database file
        run: |
          cp source/trends_data.db target/trends_data.db

      - name: Commit and push changes
        run: |
          cd target
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add trends_data.db
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Updated trends_data.db"
            git push
          fi
